version: '3.1'
services:

  achat:
    container_name: achat
    image: "achat00"
    build: .
    networks:
      - test_default   
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://tp-achat-mysql:3306/achatdb?useSSL=false
      - MYSQL_HOST=achat-mysql
      - MYSQL_USERNAME=mariem
      - MYSQL_PASSWORD=mariem
      - MYSQL_DATABASE=achatdb
    
    depends_on:
      - achat-mysql
    restart: on-failure
   
  tp-achat-mysql:
    container_name: mysql-container4
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=mariem
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=mariem
      - MYSQL_PASSWORD=mariem
    ports:
      - 3306:3306
    volumes:
      - achat-mysql-vol:/my/own/datadir       
    networks:
      - test_default   

   

volumes:
  achat-mysql-vol:
networks:
  test_default: